### ISSUE TITLE
Port 80 errors as non-root user

### ISSUE THREAD

**Issue by hildjj** [Leftium/adhoc#3]
On OSX, when run as non-root with the defaults, the following error is spit out:

```
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
---------------------------------------------
    at exports.getPort (/usr/local/lib/node_modules/adhoc/node_modules/portfinder/lib/portfinder.js:65:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/adhoc/bin/adhoc:51:12)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Module._load (module.js:312:12)
    at Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
Node NOT Exiting...
```

(then Node exits ironically)

The defaults should work out of the box.  I see several possible approaches to fix this:
- Catch the error and print something nicer than a stack trace
- Change the default port to something > 1024
- Only default to port 80 if the user is root
- Try port 80, catch the error, then try again starting at a high port
- Change portfinder to scan up from 80, which will take a long time to get to port 1024+
- Read a ~/.adhoc file for defaults

I'm happy to send a patch if you pick an approach.

**Comment by Leftium** [comment]
These options seem best:
- Try port 80, catch the error, then try again starting at a high port
- Catch the error and print something nicer than a stack trace

www.leftium.com
